# Generated by Django 5.0.6 on 2024-07-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('staff', 'Pode administrar equipes')]},
        ),
    ]
